### PR TITLE
Moving many functions from nbgui into ImageD11

### PR DESCRIPTION
**Pull request by jadball**
Apologies for the monster commit! Key highlights below:

- New GrainSinogram class to handle building sinograms from a `Grain` and `DataSet` object.
- HDF5 load/save methods for `Grain` class
- Many useful helper functions in `DataSet` class (e.g getting peaks tables for you)
- Some utility functions inside `iradon`
- Lima segmenter now uses mask and background files from the dataset object if none are manually provided
- Utility function for `blobcorrector.py` to correct a columnfile with a spline

All the diffs should be readable aside from `grain.py` which I accidentally linted (sorry!) - look at the bottom of the file for new stuff added.

### CODE REVIEW

**Comment by jadball** [comment]
This seems to be failing due to a missing hdf5plugin on py 2.7 - @jonwright any ideas? I can push a new commit in this PR to fix if you know how

**Comment by jadball** [comment]
I think the problem is that `dataset.py` now imports `properties.py` which needs `hdf5plugin` for its IO functions. We are only just now seeing this issue on Python 2.7 because we have some tests in `test_datasets.py` that are now indirectly targeting code with HDF5 I/O

**Comment by jadball** [comment]
This may be solved by adding hdf5plugin as an explicit dependency to ImageD11?

**Comment by jonwright** [comment]
We should have hdf5plugin in setup.py already:
     'hdf5plugin==1.4.1 ; python_version < "3" and sys_platform == "win32" ',
     'hdf5plugin ; python_version >= "3" ',

**Comment by jonwright** [comment]
But I guess there is a bug there as it has nothing for python2 on non-windows...

**Comment by jonwright** [comment]
I will merge and attempt to fix the CI later, the problem is not related...

**Pull request merged**
