### PR TITLE
updated patterns in Cij_symmetry 

### PR DESCRIPTION
**Pull request by jbjacob94**
updated patterns in Cij_symmetry to form the stiffness matrix in different symmetries, according to this paper:
Mouhat, F., & Coudert, F.-X. (2014). Necessary and sufficient elastic stability conditions in various crystal systems. Physical Review B, 90(22), 224104

### CODE REVIEW

**Comment by jonwright** [comment]
No - please keep the python 2 dependency! Otherwise. we cannot test it against FitAllB.

**Comment by jbjacob94** [comment]
It is just the file name, this should not affect dependencies, no?

**Comment by jonwright** [comment]
For the name I would go for something shorter, like "stress.py" for example. We can move the older code into the depreciated folder if the functionality is replaced.

**Comment by jbjacob94** [comment]
ok, go for it!

**Comment by jonwright** [comment]
If I do it now you will need to rebase / merge the change. Isn't it easier to fix the errors in Actions on this one, merge it, and then rename? You can just do:
```
git mv eps_sig_solver_NEW.py stress.py
git mv eps_sig_solver.py depreciated/
```
... and at the same time fix the typos.

**Comment by jonwright** [comment]
Are you seeing the CI?
```
# stop the build if there are Python syntax errors or undefined names
./ImageD11/stress.py:353:[18](https://github.com/FABLE-3DXRD/ImageD11/actions/runs/7179915400/job/19551108622?pr=196#step:6:19): F821 undefined name 'invariants_quantities'
        Invts = [invariants_quantities(T) for T in tensor_list]
                 ^
./build/lib.linux-x86_64-cpython-38/ImageD11/stress.py:353:18: F821 undefined name 'invariants_quantities'
        Invts = [invariants_quantities(T) for T in tensor_list]
                 ^
2     F821 undefined name 'invariants_quantities'
```

**Comment by jbjacob94** [comment]
Yes, I can see the CI. I just did a mess by mixing up different version, and was trying to restore everything back to normal. I thought all this was only happening into my branch, not on the main one. Sorry if you have received tons of error messages...

**Pull request merged**
